version: 2

sources:
  - name: erp
    description: Banco AdventureWorks
    schema: sap_adw 
    tables:

      - name: salesorderheader
        description: Descrição
        columns: 
          - name: salesorderid
            description: Descrição 
            tests:
              - unique
              - not_null
      - name: salesreason
        description: Razão da venda 